memory.limit(size = 100000)

# Load required libraries
library(readr)
library(Matrix)
library(Seurat)
require(Biobase)
library(AnnotationDbi)
library(org.Hs.eg.db)
require(stringr)
require(ggplot2)
library(BayesPrism)
library(devtools)
library(matrixStats)
library(SummarizedExperiment)
library(survival)
library(ComplexHeatmap)
library(clusterProfiler)
library(TCGAbiolinks)
library(SummarizedExperiment)
library(biomaRt)
library(e1071)
library(KEGGREST)
library(httr)
library(GSEABase)
require(reshape2)
library(dplyr)
library(glmnet)
library(pROC)
library(umap)
library(GEOquery)
library(TimeAx)
theme_set(theme_bw())
